language: cpp

git:
  depth: 10

addons:
  homebrew:
    packages:
    - git

jobs:
  include:
  - stage: macOS Build
    name: macOS
    os: osx
    cache:
      directories:
      - $HOME/SFML_OSX
      - $HOME/TGUI_OSX
    script:
      - chmod +x travis_osx.sh
      - ./travis_osx.sh